### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by giulianozor** [SuperToma/takeout-google-play-music-classify#4]
Hello,
Sorry, I’m no python expert… I have an error when running on raspberry pi

‘’’
Traceback (most recent call last):
  File "/home/pi/takeout-google-play-music-classify/classify_mp3.py", line 75, in <module>
    album = (f"({year}) " if year is not None else "") + album
TypeError: can only concatenate str (not "NoneType") to str
‘’’

I suppose some metadata is missing, but I have no idea on how to fix that…

thanks

update:
I have added a try except block and now I can at least bypass the issue. It seems related to Unicode (Japanese) characters

**Comment by smithbill17** [comment]
I get the same error on WIndows:

```
Traceback (most recent call last):
  File "C:\takeout-google-play-music-classify-main\classify_mp3.py", line 75, in <module>
    album = (f"({year}) " if year is not None else "") + album
TypeError: can only concatenate str (not "NoneType") to str
```

but i've no idea how to use a "try except block" to bypass this issue??
